### ISSUE TITLE
SettingsUtils.js:313 Uncaught (in promise) TypeError: Cannot read property 'breadcrumbs' of null

### ISSUE THREAD

**Issue by jcubic** [getmatlock/Matlock-Breadcrumbs#3]
I keep getting this error:

![matlock](https://user-images.githubusercontent.com/280241/72534451-1b63a400-3877-11ea-88e2-e32b7a198727.png)

not sure if it's related but I've instaled the extension on Chromium (have in google account) and now I'm using Google Chrome.

Example page https://terminal.jcubic.pl/404

**Comment by jcubic** [comment]
It seems it's gone, will reopen when it will happen again.

**Comment by onassar** [comment]
Hi @jcubic 
The bug is actually probably still going to come up. I submitted a fix for it to the Chrome Web Store, but it takes a few days to get through Google's submission process. Sorry about that!
